CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES(?,?,?,?,?)
"""

CREATE_BAN_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS ban_user
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
BAN_COUNT INTEGER,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_BAN_USER_QUERY = """
INSERT INTO ban_user VALUES(?,?,?)
"""

SELECT_BAN_USER_QUERY = """
SELECT * FROM ban_user WHERE TELEGRAM_ID = ?
"""

UPDATE_BAN_COUNT_QUERY = """
UPDATE ban_user SET BAN_COUNT = BAN_COUNT + 1 WHERE TELEGRAM_ID = ?
"""

CREATE_MANGA_NEWS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS manga_news(
id INTEGER PRIMARY KEY,
manga_name CHAR(100),
UNIQUE (manga_name)
)
"""

REPUTATION_CHECK_QUERY = """
SELECT BAN_COUNT FROM ban_user WHERE TELEGRAM_ID = ?
"""


INSERT_MANGA_NEWS_QUERY = """
INSERT OR IGNORE INTO manga_news VALUES(?,?)
"""

CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profile
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
BIO TEXT,
AGE INTEGER,
MARRIED CHAR(10),
GENDER CHAR(40),
FAVORITE_COLOR TEXT,
NATIONALITY TEXT,
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_PROFILE_QUERY = """
INSERT INTO profile VALUES(?,?,?,?,?,?,?,?,?,?)
"""



SELECT_PROFILES_QUERY = """
SELECT * FROM profile
"""

CREATE_LIKE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS like_profile
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
LIKER_TELEGRAM_ID INTEGER,
UNIQUE(OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
)
"""

CREATE_DIS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS dis_profile
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
diser_TELEGRAM_ID INTEGER,
UNIQUE(OWNER_TELEGRAM_ID, diser_TELEGRAM_ID)
)
"""


INSERT_LIKE_QUERY = """
INSERT OR IGNORE INTO like_profile VALUES (?,?,?)
"""

INSERT_DIS_QUERY = """
INSERT OR IGNORE INTO dis_profile VALUES (?, ?, ?)
"""

SELECT_LEFT_JOIN_PROFILE_QUERY = """
SELECT * FROM profile
LEFT JOIN like_profile ON profile.TELEGRAM_ID = like_profile.OWNER_TELEGRAM_ID
AND like_profile.LIKER_TELEGRAM_ID = ?
WHERE like_profile.ID IS NULL
AND profile.TELEGRAM_ID != ?
"""

SELECT_PROFILE_QUERY = """
SELECT * FROM profile WHERE TELEGRAM_ID = ?
"""

UPDATE_PROFILE_QUERY = """
UPDATE profile SET NICKNAME = ?, BIO = ?, AGE = ?, MARRIED = ?, GENDER = ?,FAVORITE_COLOR=?,NATIONALITY=?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""

DELETE_PROFILE_QUERY = """
DELETE FROM profile WHERE TELEGRAM_ID = ?
"""
