CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS TG_USERS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TG_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TG_ID)
)
"""


INSERT_USER_QUERY = """
INSERT INTO TG_USERS VALUES (?,?,?,?,?)
"""